# Grab all of the resources or the works
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX bflc: <http://id.loc.gov/ontologies/bflc/>
PREFIX madsrdf: <http://www.loc.gov/mads/rdf/v1#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


##############################################################################################################################################################
#
# 
#
##############################################################################################################################################################

SELECT
  ?work
  (SAMPLE(?workTitle) AS ?wt)
  (GROUP_CONCAT(DISTINCT str(?instance); separator="; ") AS ?instances)
  (GROUP_CONCAT(DISTINCT ?instanceTitle) AS ?its)
  (GROUP_CONCAT(DISTINCT str(?electronicLocator); separator="; ") AS ?eLocators)
WHERE {
  ?work
    a bf:Work , ?workType ;
    bf:hasInstance ?instance ;
    bf:title/bf:mainTitle ?workTitle ;
    # For the work, we need to get the items. These are the electronic locations 
    bf:adminMetadata ?s .
  ?instance
    bf:title/bf:mainTitle ?instanceTitle ;
  #bf:hasItem ?item ;
  .
  # The items have the electronic location items
  # Not every item has an electronic locator
  OPTIONAL {
    ?instance 
      bf:hasItem ?item .
    ?item
      bf:electronicLocator ?electronicLocator ;
      .
  }


  # The work type makes sure these aren't bare works, but works 
  # That are the basis for the resources. 
  ?workType 
    rdfs:subClassOf bf:Work .
}
GROUP BY ?work
ORDER BY ?work

